# Generated by Django 3.2.23 on 2024-01-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20240105_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='commentor',
        ),
    ]
