# Generated by Django 3.2.23 on 2024-01-10 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('account', '0005_emailaddress_idx_upper_email'),
        ('posts', '0013_auto_20240110_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
