# Generated by Django 3.2.23 on 2024-01-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20240111_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_animal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vegan_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
